<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140402173937 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");



		//$this->addSql("CREATE TABLE codingms_downloadmanager_domain_model_download (persistence_object_identifier VARCHAR(40) NOT NULL, download VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8264248D781A8270 (download), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        //$this->addSql("ALTER TABLE codingms_downloadmanager_domain_model_download ADD CONSTRAINT FK_8264248D781A8270 FOREIGN KEY (download) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE codingms_downloadmanager_domain_model_download");
	}
}
